In [1]:
import pandas as pd
import numpy as np
housing_train = pd.read_csv('kc_house_data.csv') 
tt = pd.read_csv('kc_house_data.csv') 
#엑셀 다운로드

In [2]:
housing_train.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [3]:
housing_train = housing_train.drop("id", axis=1)
train_target = housing_train["price"].copy()

In [4]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder() #각 범주를 대응하는 숫자로 변환


ordinal_encoder = OrdinalEncoder()
housing_train['date'] = pd.to_datetime(housing_train['date'])
housing_train["tr_year"] = housing_train["date"].dt.year
housing_train["tr_month"] = housing_train["date"].dt.month
housing_train["tr_day_name"] = housing_train["date"].dt.day_name
housing_train["date"] = housing_train["date"].dt.strftime('%Y-%m')
housing_train["tr_year"] = ordinal_encoder.fit_transform(housing_train[["tr_year"]])
housing_train["tr_month"] = ordinal_encoder.fit_transform(housing_train[["tr_month"]])
housing_train["tr_day_name"] = ordinal_encoder.fit_transform(housing_train[["tr_day_name"]])
housing_train["date"] = ordinal_encoder.fit_transform(housing_train[["date"]])

In [5]:
from sklearn.preprocessing import StandardScaler

# 예시: 데이터 표준화
scaler = StandardScaler()
scaler.fit_transform(housing_train)

array([[-0.12093399, -0.86671733, -0.39873715, ..., -0.69065478,
         1.09962055,  0.        ],
       [ 0.41670797, -0.00568792, -0.39873715, ..., -0.69065478,
         1.74162654,  0.        ],
       [ 0.95434994, -0.98084935, -1.47395936, ...,  1.44790136,
        -1.46840343,  0.        ],
       ...,
       [-1.19621792, -0.37586519, -1.47395936, ..., -0.69065478,
        -0.18439144,  0.        ],
       [ 0.68552895, -0.38158814, -0.39873715, ...,  1.44790136,
        -1.78940643,  0.        ],
       [-0.12093399, -0.58588173, -1.47395936, ..., -0.69065478,
         1.09962055,  0.        ]])

In [6]:
housing_train['sqft_living+bathrooms'] = housing_train['sqft_living'] + housing_train['bathrooms']
housing_train['basement_to_living_ratio'] = housing_train['sqft_basement'] / housing_train['sqft_living']
housing_train['location'] = housing_train['lat'] + housing_train['long']

housing_train['living_to_floors_ratio'] = housing_train['sqft_living'] / housing_train['floors']

housing_train['Totalviews'] = housing_train['view'] + housing_train['waterfront']
housing_train['Totalviews//'] = housing_train['view'] // housing_train['waterfront']

housing_train['Toalsizes'] = housing_train['sqft_living'] + housing_train['sqft_above'] + housing_train['sqft_basement'] + housing_train['sqft_living15']



housing_train["house_per_sqft_livings"] = 1 / (housing_train["sqft_living"] + housing_train["sqft_living15"])

housing_train['(sqft_living*grade)/2'] = (housing_train['sqft_living'] * housing_train['grade']) / 2


housing_train['(sqft_living//waterfront/sqft_living)'] = ((housing_train['sqft_living']))//(housing_train['waterfront']/housing_train['sqft_living'])


housing_train["sqft_living*waterfront"] = housing_train["sqft_living"] * housing_train["waterfront"]


# #삭제될 예정
# housing_train['(sqft_living//waterfront/sqft_living)'] = ((housing_train['sqft_living']))//(housing_train['waterfront']/housing_train['sqft_living'])
housing_train['(waterfront//waterfront/sqft_living)'] = (housing_train['waterfront']//(housing_train['waterfront']/housing_train['sqft_living']))
housing_train['((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living))'] = housing_train['(sqft_living//waterfront/sqft_living)']//housing_train['(waterfront//waterfront/sqft_living)']
# #삭제될 예정
housing_train['(waterfront/waterfront/sqft_living)'] = (housing_train['waterfront']/housing_train['waterfront']/housing_train['sqft_living'])
housing_train['(sqft_living**2)//(waterfront/waterfront/sqft_living)'] = (housing_train['sqft_living']**2)//(housing_train['(waterfront/waterfront/sqft_living)'])

# #삭제될 예정
housing_train['(waterfront//(waterfront/sqft_living))'] = housing_train['waterfront']//(housing_train['waterfront']/housing_train['sqft_living'])#(sqft_living//((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living)) ## 89.7
housing_train['(sqft_living//((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living))'] = ((housing_train['sqft_living']) // ((housing_train['(sqft_living//waterfront/sqft_living)'])) // (housing_train['(waterfront//waterfront/sqft_living)']))

# #사용될 예정
housing_train['(waterfront//waterfront/sqft_living/(sqft_living//((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living))))'] = housing_train['(waterfront//waterfront/sqft_living)'] / housing_train['(sqft_living//((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living))']
housing_train['((sqft_living**2)//(waterfront//(waterfront/sqft_living)))'] = ((housing_train['sqft_living']**2)//(housing_train['waterfront']//(housing_train['waterfront']/housing_train['sqft_living'])))

housing_train['(((waterfront//waterfront/sqft_living))/((((waterfront//waterfront/sqft_living))//(((sqft_living**2)//(waterfront//(waterfront/sqft_living)))))))']= (((housing_train['(waterfront//waterfront/sqft_living)'])/((((housing_train['(waterfront//waterfront/sqft_living)']))//(housing_train['((sqft_living**2)//(waterfront//(waterfront/sqft_living)))'])))))



housing_train = housing_train.drop('(waterfront//waterfront/sqft_living)', axis=1)
housing_train = housing_train.drop('(waterfront/waterfront/sqft_living)', axis=1)
housing_train = housing_train.drop('(sqft_living**2)//(waterfront/waterfront/sqft_living)', axis=1)
housing_train = housing_train.drop('(sqft_living//((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living))', axis=1)
housing_train = housing_train.drop('(waterfront//waterfront/sqft_living/(sqft_living//((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living))))', axis=1)
housing_train = housing_train.drop('(sqft_living//waterfront/sqft_living)', axis=1)

housing_train = housing_train.drop('((sqft_living//waterfront/sqft_living)//(waterfront//waterfront/sqft_living))', axis=1)
housing_train = housing_train.drop('(waterfront//(waterfront/sqft_living))', axis=1)

In [7]:
corr_matrix = housing_train.corr()
corr_matrix["price"].sort_values(ascending=False)

price                                                                                                                                                1.000000
((sqft_living**2)//(waterfront//(waterfront/sqft_living)))                                                                                           0.878835
(((waterfront//waterfront/sqft_living))/((((waterfront//waterfront/sqft_living))//(((sqft_living**2)//(waterfront//(waterfront/sqft_living)))))))    0.846761
(sqft_living*grade)/2                                                                                                                                0.756279
Toalsizes                                                                                                                                            0.705189
sqft_living                                                                                                                                          0.702035
sqft_living+bathrooms                                                                                                                                0.702031
grade                                                                                                                                                0.667434
sqft_above                                                                                                                                           0.605567
sqft_living15                                                                                                                                        0.585379
bathrooms                                                                                                                                            0.525138
living_to_floors_ratio                                                                                                                               0.432677
Totalviews                                                                                                                                           0.406834
view                                                                                                                                                 0.397293
sqft_living*waterfront                                                                                                                               0.342536
sqft_basement                                                                                                                                        0.323816
bedrooms                                                                                                                                             0.308350
lat                                                                                                                                                  0.307003
waterfront                                                                                                                                           0.266369
floors                                                                                                                                               0.256794
location                                                                                                                                             0.248157
basement_to_living_ratio                                                                                                                             0.135539
yr_renovated                                                                                                                                         0.126434
Totalviews//                                                                                                                                         0.093146
sqft_lot                                                                                                                                             0.089661
sqft_lot15                                                                                                                                           0.082447
yr_built                                                                                                                                             0.054012
condition                                                                                                                                            0.036362
long                                                                                                                                                 0.021626
tr_year                                                                                                                                              0.003576
date                                                                                                                                                -0.003048
tr_month                                                                                                                                            -0.010081
zipcode                                                                                                                                             -0.053203
house_per_sqft_livings                                                                                                                              -0.548914
tr_day_name                                                                                                                                               NaN
Name: price, dtype: float64

In [8]:

filtered_train_data = housing_train.drop('price', axis=1)
filtered_train_data.replace([np.inf, -np.inf], np.nan, inplace=True)

In [9]:
# import numpy as np
# import pandas as pd
# from catboost import CatBoostRegressor
# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import cross_val_score

# # 데이터 불러오기 (가상의 데이터로 예시)
# # 여기서는 filtered_train_data와 train_target를 적절한 방법으로 불러와야 합니다.
# # filtered_train_data와 train_target는 사용자의 실제 데이터에 대응되어야 합니다.

# # # k-폴드 CV의 평균을 계산하기 위한 함수
# def display_scores(scores):
#     print("Scores:", scores)
#     print("Mean:", scores.mean())
#     print("Standard deviation:", scores.std())

# # 기본 시드 설정
# seed = 21366
# # 데이터 섞기
# np.random.seed(seed)
# sh_in = np.random.permutation(len(filtered_train_data))
# sh_t_data = filtered_train_data.values[sh_in]
# sh_t_target = train_target.values[sh_in]

# best=0
# for i in range(2000,2500, 50):
#     # CatBoostRegressor 초기화
#     catboost = CatBoostRegressor(iterations=i, depth=7, learning_rate=0.1, verbose=0)

#     # 교차 검증 수행
#     best_model_scores = cross_val_score(catboost, sh_t_data, sh_t_target, scoring='neg_mean_squared_error', cv=10, n_jobs=-1)
#     best_model_rmse_scores = np.sqrt(-best_model_scores)

#     # 결과 출력
#     print(f"현재{i}")
#     display_scores(best_model_rmse_scores)
#     if best < best_model_rmse_scores.mean():
#         best = best_model_rmse_scores.mean()
#         print(f"최댓값{i}, best: {best}")

106523

In [10]:
import numpy as np
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

seed = 21366

# 데이터 섞기
np.random.seed(seed)
sh_in = np.random.permutation(len(filtered_train_data))
sh_t_data = filtered_train_data.values[sh_in]
sh_t_target = train_target.values[sh_in]

catboost = CatBoostRegressor(iterations=2150, depth=7, learning_rate=0.1, verbose=0)

# 교차 검증 수행
best_model_scores = cross_val_score(catboost, sh_t_data, sh_t_target, scoring='neg_mean_squared_error', cv=10, n_jobs=-1)
best_model_rmse_scores = np.sqrt(-best_model_scores)

# 결과 출력
display_scores(best_model_rmse_scores)

Scores: [122356.0585723   94525.11577057 117023.29225805  83658.46773186
 105816.08587519 121512.7538352  105409.37543464  96182.54885984
 106716.11065667 111978.20484629]
Mean: 106517.80138405979
Standard deviation: 11793.353049668316